language: node_js
node_js:
  - 'stable'

before_install:
  - cd exam

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: exam/build
  on:
    branch:
      - master
      - exam
